### ISSUE TITLE
Can not login when installing the app in Teams

### ISSUE THREAD

**Issue by isinadinos** [sinedied/teams-schematics#21]
I deployed the static app in azure and when uploaded app/manifest in teams I get the following error:

`ERROR Error: Uncaught (in promise): BrowserAuthError: redirect_in_iframe: Redirects are not supported for iframed or brokered applications. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true`

No changes made in login process.

**Comment by sinedied** [comment]
cc @waldekmastykarz

**Comment by waldekmastykarz** [comment]
Hey @isinadinos, are you testing the app in Teams on the web or the desktop/mobile app?

**Comment by isinadinos** [comment]
@waldekmastykarz I am testing on both. On desktop web app I get the following error and inside Teams I press the sign in button and nothing happens (I can not see any errors in Teams app).

![image](https://user-images.githubusercontent.com/7393234/233006426-e95e3ce5-453b-47df-9ea0-98834113dc50.png)

**Comment by waldekmastykarz** [comment]
Have you created and configured the AAD app manually or have you used the script provided with the schematic?

**Comment by isinadinos** [comment]
I have created the app manually from Azure Portal and chaged the values in the provided manifest.json

**Comment by waldekmastykarz** [comment]
Could you please try using the instructions from the project? I wonder if the behavior that you're seeing could be caused by the app using different settings.

**Comment by isinadinos** [comment]
On the first step "node scripts/update-manifest.js <production_url>" I get an error and can not proceed.

 ```
> node .\scripts\update-environment.js "https://white-plant-xxxx.azurestaticapps.net"

node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\neurocom\neurocomteams\.m365rc.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getAppId (C:\neurocom\neurocomteams\scripts\update-environment.js:46:29)
    at updateEnvironment (C:\neurocom\neurocomteams\scripts\update-environment.js:21:17)
    at run (C:\neurocom\neurocomteams\scripts\update-environment.js:17:3)
    at Object.<anonymous> (C:\neurocom\neurocomteams\scripts\update-environment.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\neurocom\\neurocomteams\\.m365rc.json'
}
```

Also at step 2 when login, asks for admin permissions for PnP Management which is not clear in Azure which permissions should be granded. We should not give all permissions when we only need to read users for organization.

**Comment by waldekmastykarz** [comment]
If I follow the steps from the readme of this repo, and then in the readme of the scaffolded project, it's all working for me as expected:

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/11164679/233072150-4afdcedf-2231-4ce1-9ea1-816f9f497260.png">

> Also at step 2 when login, asks for admin permissions for PnP Management which is not clear in Azure which permissions should be granded. We should not give all permissions when we only need to read users for organization.

CLI for Microsoft 365 is a tool that we use to create the Azure AD app registration. So this permission prompt is not for your Teams app itself, but rather for creating the resources for it. If you prefer, you can create your own Azure AD app registration with minimal permissions for use with CLI for Microsoft 365. For more information about this, see https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity/

**Comment by isinadinos** [comment]
Hi @waldekmastykarz. This is the login page (LoginComponent) which also appears correctly in my case. In the end of this page there is a button for sign in microsoft. When pressing this button to sign in, then the problem appears described above. Did you press the button? 
Also, from the guard code I expect that since the app is "inTeams" you should be redirected to HomeComponent and I expect to see a "home works!". 
So what is the expected behaviour? When testing locally I should see the button and sign in and when inTeams the sign in is done automatically?

**Comment by waldekmastykarz** [comment]
Yes, I pressed the button and completed the login flow. When opening the app in Teams, I'm getting directly past sign in because I'm already signed in to Teams.

**Comment by isinadinos** [comment]
The problem was caused because in my tsconfig.json the value was automatically set to "strict": true, and this makes the teams.guard.ts fail in lines 60-72, and I had to change the code to pass. In yours tsconfig.json you are only using the  the property "strictNullChecks": true.

So other devs should have a look in the tsconfig.json and strict policies if they come up to this error.

**Comment by waldekmastykarz** [comment]
Thanks for sharing! I'm sure it will be helpful for others to know!
